hbz/oerworldmap-ui

package.json, src/client.js, src/components/ActionButtons.js, src/components/App.js, src/components/Column.js, src/components/Filters.js, src/components/Header.js, src/components/Icon.js, src/components/ItemList.js, src/components/Link.js, src/components/Metadata.js, src/components/NotificationWelcome.js, src/components/WebPage.js, src/locale/de.json, src/locale/en.json, src/locale/es.json, src/styles/Columns.pcss, src/styles/Filters.pcss, src/styles/ItemList.pcss, src/styles/Metadata.pcss, src/styles/main.pcss, webpack.config.babel.js
THis branch also includes the change to the :target :dart:  selector.
=> Filters style

src/api.js, src/client.js, src/server.js
Note: automated second request to receive GeoJSON features has been removed,
these will be added to the initial API response.
=> Use Promises when loading from and saving to API

src/components/Statistics.js, src/components/WebPage.js
We have a warring also in http://oerworldmap.graphthinking.com/
=> Remove warnning by moving prop

src/components/Comments.js, src/components/Label.js, src/components/WebPage.js, src/json/schema.json, src/router.js, src/styles/components/WebPage.pcss
Examples for entries with comments: http://oerworldmap.graphthinking.com/resource/?q=_exists_:about.comment&size=30
=> Add Comment section

src/components/Country.js
@dobladov I deployed the corresponding back end fix to dev.
=> Fix aggregations in country view

src/components/WebPageView.js, src/styles/components/ItemList.pcss
e.g.:
/resource/urn%3Auuid%3A044ee293-d4a4-4ace-8127-b6c52f971ec3
/resource/urn%3Auuid%3A15fdc244-c227-42a4-bf87-907c8a4fcc0f
=> style awards

src/components/Share.js
Fix for hbz/oerworldmap-ui#201
=> Encode URL in share links

src/components/ButtonFilter.js, src/styles/components/Filters.pcss
=> 200 unset type filter

src/components/Filters.js
=> Disable render of page select for events

src/locale/descriptions.properties
=> Add note to Lighthouse form

package.json, src/client.js, src/components/Filters.js, src/styles/components/Filters.pcss
=> 226 fix form data for safari

src/components/WebPageUserActions.js
Deploy after https://github.com/hbz/oerworldmap/commit/046b0fb3c10c66412ac7b6fdc0f7c5445e86256f
=> Allow lighthouses and likes for Events

src/router.js, src/styles/components/Feedback.pcss
=> Use FullModal for feedback messages

src/components/JSONPointerForm/Builder.js, src/components/JSONPointerForm/DropdownSelect.js, src/components/JSONPointerForm/Fieldset.js, src/components/JSONPointerForm/Input.js, src/components/JSONPointerForm/KeywordSelect.js, src/components/JSONPointerForm/List.js, src/components/JSONPointerForm/PlaceWidget.js, src/components/JSONPointerForm/RemoteSelect.js, src/components/JSONPointerForm/Select.js, src/components/JSONPointerForm/Textarea.js, src/locale/ui.properties, src/styles/components/FormStyle.pcss
=> Style labels for required fields

src/components/Statistics.js
@trugwaldsaenger let us know if you want any other stats reordered
Fixes #230
=> Move primary above secondary sector in stats

src/components/JSONPointerForm/Builder.js, src/components/JSONPointerForm/Input.js, src/components/JSONPointerForm/PlaceWidget.js
Fixes #237
See https://github.com/hbz/oerworldmap/commit/195d229751469ab3cd6f0ed3dfaac878d3fb8aed
=> Only use placeholders explicitly from schema

src/components/JSONPointerForm/Builder.js, src/components/JSONPointerForm/LocalizedString.js, src/styles/components/FormsStructure.pcss
=> Default to English when using multilingual input

src/components/WebPageView.js
=> Move awards and licenses below likes in sidebar

src/components/Map.js, src/styles/base.pcss, src/styles/components/Map.pcss
=> Print styles

src/components/Filters.js
Fixes #257
Needs https://github.com/hbz/oerworldmap/commit/b2422969b859b884b8d4eafec9d20d1325ad78d6
=> Set default sort order based on query string

src/styles/components/FormStyle.pcss
=> Set max-width for dropdowns

src/components/ResourceIndex.js, src/router.js
=> Pass missing view prop

src/common.js, src/components/ButtonFilter.js, src/components/Filters.js, src/styles/components/Columns.pcss
=> Retain search term when clearing/changing filters

src/components/DropdownFilter.js
=> Hide and show filters instead of recreating the list

src/client.js, src/views/index.js
=> OER World Map in titles

src/components/Filters.js
=> Force new input when search term changes

src/components/JSONPointerForm/Builder.js
=> Fix stale form components when schema changes

src/common.js
=> Show three dots for longers URLs

docs/_data/locale/descriptions.json, docs/_data/locale/labels.json, docs/_data/locale/ui.json
Together with https://github.com/hbz/oerworldmap/pull/1525 this will resolve https://github.com/hbz/oerworldmap/issues/1513
=> Add labels & description for tool license information

src/components/JSONPointerForm/PlaceWidget.js
Also, don't clear address when a region is changed.
Fixes hbz/oerworldmap#1495
=>  Show address along with region on country select

src/components/MiniMap.js
=> Replace FlyTo for FitBounds to fix the Position Bug

src/components/JSONPointerForm/RemoteSelect.js, src/styles/components/FormStyle.pcss, src/styles/components/FormsStructure.pcss
=> Add new level of Indention

docs/_data/locale/labels.json, src/components/ButtonFilter.js, src/components/Filters.js, src/styles/base.pcss
=> Add new messages and styles for the tooltip info

src/components/ConceptTree.js
=> Fix modified reference inside filterConcepts

src/components/JSONPointerForm/RemoteSelect.js, src/json/organizations.json, src/json/persons.json, src/json/projects.json, src/json/publications.json, src/json/services.json
Also add English labels for Portuguese interface. Fixes https://github.com/hbz/oerworldmap/issues/1543
=> Add German labels

src/json/services.json
=> Add content source to service type vocab

src/router.js
=> Use same images as /resource/ for country view

src/components/JSONPointerForm/PlaceWidget.js, src/styles/components/FormStyle.pcss
=> Hide labels for embedded Grants

package.json, src/components/JSONPointerForm/MarkdownArea.js, src/components/JSONPointerForm/PlaceWidget.js, src/components/MiniMap.js, src/components/WebPageCover.js, src/router.js
=> Refactor Minimap

src/components/JSONPointerForm/PlaceWidget.js, src/styles/components/FormStyle.pcss
=> Show location label when is collapsed

src/json/esc.json
Fixes https://github.com/hbz/oerworldmap/issues/573
=> Fix encoding issue in subject suggestions

src/components/DropdownFilter.js, src/components/Filters.js, src/components/Map.js, src/router.js
See https://github.com/hbz/oerworldmap/pull/1611/commits/2a713e48771c772dfaadde064cfb58046c383576
=> Use global facet aggregation in filter section

src/styles/components/ItemList.pcss
Fixes: hbz/oerworldmap#1597
https://oerworldmap.org/resource/urn:uuid:6a98d2cc-2117-4fa4-94e7-6c79ccdf6bdb
=> Fix spacing and scroll for lists

package.json, src/server.js
=> Return message in case of using internet explorer

src/components/Country.js
=> Order reports by dateCreated

src/components/SocialLinks.js
=> Add Pinterest icon

src/components/ItemList.js, src/styles/base.pcss
=> Add date to events in ItemList

src/components/Country.js
Fixes: hbz/oerworldmap#1596
The problem was a missing translation.
=> Add missing translation of label

src/components/WebPageView.js, src/styles/components/WebPageView.pcss
=> Set styles for stories in WebpageView

src/components/JSONPointerForm/DropdownSelect.js, src/components/JSONPointerForm/Input.js, src/components/JSONPointerForm/KeywordSelect.js, src/components/JSONPointerForm/List.js, src/components/JSONPointerForm/MarkdownArea.js, src/components/JSONPointerForm/Select.js, src/components/JSONPointerForm/Textarea.js, src/styles/components/FormStyle.pcss
=> Add asterisk with title for required checkboxes

src/components/WebPageView.js
=> Add possiblilty to link to an ID

src/styles/components/ItemList.pcss
=> Fix styles for events in WebpageVIew

src/components/WebPageCover.js
=> Use avatars.io to load the twitter profile image

src/components/ErrorBoundary.js, src/components/WebPageView.js
=> Add ErrorBoundary component to fix wrong markup rendering

docs/_data/locale/ui.json, src/components/WebPageView.js
=> Extract i18n for entries missing information

src/components/WebPageView.js
Fixes https://github.com/hbz/oerworldmap/issues/1636
=> Add publication date to item view

src/components/Map.js
=> Show if there is a country champion if the view is not a selected country

docs/_data/locale/labels.json
changed "Product.image": "Image" to "Product.image": "Logo"
=> minor change

.eslintrc, .travis.yml, package.json, src/components/Calendar.js
=> Scroll to the month

src/components/WebPageUserActions.js
Fixes https://github.com/hbz/oerworldmap/issues/1650
=> Add like and lighthouse to story and publication

src/components/Calendar.js, src/styles/components/Calendar.pcss
Fixed scroll movement bug https://stackoverflow.com/a/42056880
=> Fix ScrollIntoView Bug

src/components/MiniMap.js
Fixes: https://github.com/hbz/oerworldmap/issues/1640
=> Update the zoom on mouseUp

src/components/Calendar.js, src/components/ItemList.js, src/components/JSONPointerForm/RemoteSelect.js
Fixes: https://github.com/hbz/oerworldmap/issues/1268 Fixes: https://github.com/hbz/oerworldmap/issues/1433
=> Add alternateName

docs/_data/locale/ui.json, src/components/Calendar.js
See https://github.com/hbz/oerworldmap/issues/1178
=> Hide past events by default instead of scrolling

src/common.js, src/components/ItemList.js, src/components/Map.js, src/components/ResourceImage.js, src/components/ResourceIndex.js, src/components/ResourcePreview.js, src/components/WebPageCover.js, src/public/lighthouse_16px_grey.svg, src/router.js, src/styles/base.pcss, src/styles/components/ItemList.pcss, src/styles/components/Map.pcss, src/styles/components/ResourceImage.pcss, src/styles/components/ResourcePreview.pcss, src/styles/components/WebPage.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1667, Fixes: https://github.com/hbz/oerworldmap/issues/1669 Fixes: https://github.com/hbz/oerworldmap/issues/1663
=> Add translate to alternate name

src/components/Metadata.js, src/components/Topline.js, test/Metadata.js
Fixes: https://github.com/hbz/oerworldmap/issues/1665
=> Move additionalTypes for Topline to Metadata

src/components/WebPageView.js
Fixes: https://github.com/hbz/oerworldmap/issues/1664
=> Change icon to fa-thumbs-up

src/components/JSONPointerForm/MarkdownArea.js, src/styles/components/Comments.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1666
=> Add space and pass placeholder variable

docs/_data/locale/descriptions.json, docs/_data/locale/labels.json, docs/_data/locale/ui.json, src/api.js, src/components/Filters.js, src/components/WebPageView.js, src/json/activities.json
See https://github.com/hbz/oerworldmap/issues/144
=> Add label and description for activity fields

.eslintignore, package.json, src/components/JSONPointerForm/Builder.js, src/components/JSONPointerForm/DateTime.js, src/styles/components/FormsStructure.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1151
Also add  `"_widget": "DateTime"` to the schema in [oerworldmap](https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json#L3296)
=> Add DateTime component

docs/about.md
Fixes: https://github.com/hbz/oerworldmap/issues/1592
=> Set set size of image to use all width

docs/oerpolicies.md
See: https://github.com/hbz/oerworldmap/issues/1684
=> Add oerpolicies static page

docs/_data/locale/labels.json, src/styles/components/FormStyle.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1676
Merge with: https://github.com/hbz/oerworldmap/pull/1686
=> Add style for citation

docs/about.md, docs/api.md
FIxes: https://github.com/hbz/oerworldmap/issues/1306
=> Add license to about and api

docs/_data/locale/ui.json, src/components/Header.js
Fixes: https://github.com/hbz/oerworldmap/issues/8
=> Add CountryChampions link

src/components/Header.js
See https://github.com/hbz/oerworldmap/pull/1685
=> Use user ID in filter links

src/components/Columns.js, src/components/ResourceIndex.js, src/router.js, src/styles/components/Columns.pcss, src/styles/components/Country.pcss, src/views/index.js
Fixes: https://github.com/hbz/oerworldmap/issues/1225
=> Fix counrty view styles for mobile

src/components/WebPageHeader.js, src/router.js
Fixes: https://github.com/hbz/oerworldmap/issues/1690
=> Add link back to feed

docs/contribute.md
Fixes: https://github.com/hbz/oerworldmap/issues/839
=> Add Text and link to register in contribute page

src/components/Map.js
See https://github.com/hbz/oerworldmap/pull/1700
=> Use global country champion aggregation

src/components/Filters.js, src/components/Map.js, src/router.js
See https://github.com/hbz/oerworldmap/pull/1701
=> Use filtered gobal facets aggregation

docs/_data/locale/ui.json, src/components/Header.js
Fixes: https://github.com/hbz/oerworldmap/issues/1519
=> Add information to add menu

src/components/Register.js
Fixes: https://github.com/hbz/oerworldmap/issues/1724
=> Remove emit event for login

docs/_data/locale/ui.json, src/common.js, src/components/JSONPointerForm/DateTime.js, src/components/JSONPointerForm/DropdownSelect.js, src/components/JSONPointerForm/Fieldset.js, src/components/JSONPointerForm/Form.js, src/components/JSONPointerForm/Input.js, src/components/JSONPointerForm/KeywordSelect.js, src/components/JSONPointerForm/List.js, src/components/JSONPointerForm/MarkdownArea.js, src/components/JSONPointerForm/PlaceWidget.js, src/components/JSONPointerForm/RemoteSelect.js, src/components/JSONPointerForm/Select.js, src/components/JSONPointerForm/Textarea.js, src/styles/components/FormStyle.pcss, src/styles/components/Password.pcss
Fixes: https://github.com/hbz/oerworldmap-ui/issues/232, Fixes: https://github.com/hbz/oerworldmap/issues/1536, Fixes: https://github.com/hbz/oerworldmap/issues/1577
=> Update error messages and trim data

src/components/Pagination.js
Fixes: https://github.com/hbz/oerworldmap/issues/1687
=> Scroll up when pagination buttons are pressed

.babelrc, package.json, src/components/App.js, webpack.config.babel.js
Remove react-hot-loader and checks for style on every compile
=> Simpler config

src/components/WebPageView.js, src/styles/components/WebPageView.pcss
=> 1720 tab description

src/components/Statistics.js, src/router.js, src/styles/components/Statistics.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1711
=> Refactor Statistics to use kibana

src/components/Country.js, src/styles/components/Country.pcss, src/styles/components/FullModal.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1467
=> 1467 country statistics

src/components/Filters.js
Fixes: https://github.com/hbz/oerworldmap/issues/1346
=> 1346 order countries

src/components/WebPageView.js, src/styles/helpers.pcss
Before: ![image](https://user-images.githubusercontent.com/1938043/50767372-d2007200-127c-11e9-9d78-967293320681.png)
---
After:
=> Move alternateName position

src/components/ItemList.js, src/components/WebPageView.js
Fixes: https://github.com/hbz/oerworldmap/issues/1409
=> Add Lighthouses and Likes to profile

src/components/Header.js, src/styles/components/Header.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1491
=> Add search input to header

docs/_includes/_landingpage/contribute.html, docs/_includes/_landingpage/examples.html
Fixes: https://github.com/hbz/oerworldmap/issues/1429
Not finished yet, we need to think how to convert the IP of the visitor to their country.
=> Add links to examples and contribute

src/server.js
Fixes https://github.com/hbz/oerworldmap/issues/1741
=> Assign default values to phrases

docs/_data/locale/labels.json, src/api.js, src/components/Header.js, src/components/WebPageView.js, src/json/policyTypes.json
See https://github.com/hbz/oerworldmap/issues/1768
=> Policy types

src/components/WebPage.js, src/components/WebPageView.js, src/styles/base.pcss, src/styles/components/ItemList.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1767
=> 1767 remove map header

src/components/Filters.js, src/styles/components/Filters.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1771
=> 1771 unset selected filter

src/components/WebPageUserActions.js
Fixes: https://github.com/hbz/oerworldmap/issues/1781
=> Add type policy to show toggleLike and addLighthouse

src/components/Country.js, src/components/Map.js, src/styles/components/Columns.pcss, src/styles/components/Country.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1778
Merge after branch [1773-MoveColumnToLeft](https://github.com/hbz/oerworldmap-ui/tree/1773-MoveColumnToLeft) from issue #495
=> 1778 rearange close country icon

src/components/Columns.js, src/components/Filters.js, src/components/Map.js, src/styles/components/Columns.pcss, src/styles/components/Country.pcss, src/styles/components/Filters.pcss, src/styles/components/Map.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1777
Merge after branch [1773-MoveColumnToLeft](https://github.com/hbz/oerworldmap-ui/tree/1773-MoveColumnToLeft) from issue #495
=> 1777 rearrange show list button

src/components/Filters.js, src/styles/components/Columns.pcss, src/styles/components/Filters.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1780
=> Add clear fliters button next to search

docs/_data/locale/ui.json, src/components/Filters.js, src/components/ResourceIndex.js, src/styles/components/Filters.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1766
Merge when we definitely agree on the content for the placeholder.
=> Pass the country to filters and set a new placeholder

src/components/ResultList.js, src/styles/components/ResultList.pcss
=> Add icon, move location and minor fixes for spacing

src/components/Map.js, src/styles/components/Map.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1528
=> Refactor popup functionalty for map

src/components/Map.js
Fixes: https://github.com/hbz/oerworldmap/issues/1815
=> Refactor updateZoom for small countries

src/components/Header.js
Fixes: https://github.com/hbz/oerworldmap/issues/1820
=> Set header link to /

src/components/Filters.js, src/styles/components/Filters.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1819
=> Add new button to collapse filter and increase the size of the list

src/router.js
Fixes: https://github.com/hbz/oerworldmap/issues/1823
=> Add login message for add route without user

src/components/WebPage.js, src/components/WebPageView.js
Fixes: https://github.com/hbz/oerworldmap/issues/1818
=> Show login for edit messge if there is no user

src/components/Filters.js
Fixes: https://github.com/hbz/oerworldmap/issues/1841
=> Set a minumum of 20 results to show the selector

src/styles/components/ResultList.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1840
=> Fix Chrome resize of flex list

src/components/Country.js, src/styles/components/Country.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1834
=> Add option to minimize the country box

src/styles/components/MobileNavigation.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1836
=> Increase area of icons for mobile

src/components/Map.js
Fixes: https://github.com/hbz/oerworldmap/issues/1843
=> Fix location for ResourcePreview

src/components/Diffs.js, src/components/JSONPointerForm/Builder.js, src/components/ResourceImage.js, src/components/WebPage.js, src/components/WebPageCover.js
Fixes: https://github.com/hbz/oerworldmap/issues/1845
=> Scroll to the image imput when id is undefined

src/components/Filters.js, src/components/Map.js, src/components/ResourceIndex.js, src/styles/components/Columns.pcss, src/styles/components/Filters.pcss, src/styles/components/Map.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1842
=> Move pins control to Filters

src/server.js
Fixes: https://github.com/hbz/oerworldmap/issues/1865
=> Fix object deconstruction

src/client.js
=> Fix matomo Titles

docs/_data/locale/descriptions.json, docs/_data/locale/labels.json, src/components/WebPageView.js
See https://github.com/hbz/oerworldmap/projects/8
=> Add fields, labels and descriptions

src/styles/components/Header.pcss
Fixes this scroll while hovering the last element.
=> Fix header overflow on the last element

src/client.js, src/common.js, src/components/Header.js, src/router.js
Fixes: https://github.com/hbz/oerworldmap/issues/1862
=> 1862 language switch fix

src/client.js
Based on this response we should use hydrate for the client https://stackoverflow.com/a/46516869/2498992
=> Use hydrate in client instead of render

docs/_data/locale/labels.json, src/components/Block.js, src/components/ItemList.js, src/components/WebPageView.js, src/styles/components/Block.pcss, src/styles/components/ItemList.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1801#event-2572339552
Don't merge until we decide if we want to add the `+ Add` anchor button toe each column
=> 1801 item list

src/components/Columns.js
As mentioned here: https://oerworldmap.slack.com/archives/G7Q8RJZT2/p1567503963005600
=> Replace gif for one not showing the dots

src/components/JSONPointerForm/LocalizedString.js
Fixes: https://github.com/hbz/oerworldmap/issues/1870
=> Order languagesAvailable based on the selected language

src/common.js
Fixes: https://github.com/hbz/oerworldmap/issues/1875
=> Don't use moment to fortmat a single year

docs/_data/locale/ui.json, src/components/Block.js, src/components/Filters.js, src/components/ResourceIndex.js, src/components/ResultList.js, src/components/WebPageView.js, src/styles/components/ResultList.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1864
=> 1864 clarify lighthouses

src/components/Map.js
Fixes: https://github.com/hbz/oerworldmap/issues/1883
=> Refactor move using an URL object

src/components/Header.js
Fixes: https://github.com/hbz/oerworldmap/issues/1885
=> Add language to profile link

src/components/Header.js
Fixes: https://github.com/hbz/oerworldmap/issues/1884
=> Add view to redirect to edit while changing language

docs/_data/locale/ui.json, src/components/WebPageView.js
Fixes: https://github.com/hbz/oerworldmap/issues/1890
=> Add Icon and h4 for links

src/components/WebPageView.js, src/styles/components/WebPageView.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1891
=> Add pulsate animation for hashtag button

src/components/ReactiveFilters.js, src/components/ReactiveMap.js, src/components/ReactiveResourceIndex.js
Hides live events also with TogglePins button
=> fix: Toggle liveEvents pins

src/components/ReactiveFilters.js
@gandalfar this should fix the issue, please test on a dev machine though!
Fixes https://github.com/hbz/oerworldmap/issues/1916
=> Filter on aggregated / inherited locations

src/components/ReactiveMap.js
=> Fix max doc_count in map legend

src/components/ReactiveFilters.js
=> Use custom query in DataSearch

src/i18ns.js, src/json/policies.json, src/server.js
=> Fix labels in policy type vocab

src/components/JSONPointerForm/KeywordSelect.js, src/components/ReactiveFilters.js
=> Fix keyword list

src/components/WebPage.js, test/resources/user.json
=> Render only edit or view instead of CSS hiding

src/components/WebPage.js, src/styles/base.pcss, src/styles/components/FormStyle.pcss
Fixes https://github.com/hbz/oerworldmap/issues/1921
=> Fix display of admin only fields

src/components/Comments.js, src/components/WebPageView.js
Fixes hbz/oerworldmap#1947, fixes #641
=> Fix missing user prop and login link

README.md, startup.sh
See https://github.com/hbz/oerworldmap-ui/issues/640.
=> Use proper node version in startup-script and README

docs/_data/locale/descriptions.json, docs/_data/locale/labels.json, src/components/WebPageView.js
This complements https://github.com/hbz/oerworldmap/pull/1942, see hbz/oerworldmap#1938
=> Add reference number field

docs/_data/locale/descriptions.json, docs/_data/locale/labels.json, src/common.js, src/components/Header.js, src/components/Icon.js, src/components/WebPageView.js, src/styles/components/ResourceIndex.pcss
=> Add Collection type to UI
