- src/client.js
- src/components/Link.js
So far we were bypassing `renderApp` and therefor also not updating the route props when triggering a URL change with a hash. In order to properly update the route passed down to the app, `renderApp` needs to be called on every URL change.
> Update route prop also on hash change

- src/client.js
- src/components/Comments.js
- src/components/Lighthouses.js
- src/components/WebPageUserActions.js
- src/components/WebPageView.js
In some cases, such as when creating and deleting a `LikeAction` or a `LighthouseAction`, we don't want to go to the new URL, we want to stay on the current `WebPage`. For this, the `delete` and `submit` events now support a `redirect` parameter.
> Route to resource after action

- src/styles/components/ItemList.pcss
Error caused  by this bug [Firefox: break-word doesn't work inside flex items](https://github.com/philipwalton/flexbugs/issues/39)
Using this solution to fix it.
[Flexbox and Truncated Text](https://css-tricks.com/flexbox-truncated-text/)
> Add fix for truncated texts

- src/components/WebPageView.js
Related to https://github.com/hbz/oerworldmap/issues/1499.
**We still need to remove hide displayName in the Schema.**
> Remove displayName for WebPageview

- src/components/Country.js
> Change question mark icon to user for CountryChampions without image

- src/components/JSONPointerForm/Builder.js
- src/components/JSONPointerForm/JsonSchema.js
This is a first fix for https://github.com/hbz/oerworldmap/issues/1648. While the UI is still confusing because all fields from alternate schema `required`s are marked as required, it at least allows to save valid data again.
> Don't merge original schema when expanding

- src/components/FullModal.js
- src/components/WebPage.js
Fixes: https://github.com/hbz/oerworldmap/issues/1521
Now is possible to go back by clicking on the empty wrapper of a modal, and in edit view the user will be prompt to go back.
Refactor to not use querySelector when we can create refs with React hocks.
> Add possiblity to close modals with a click outside the dialog

- package.json
- src/components/WebPageView.js
- src/styles/components/WebPageView.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1453, also see: https://github.com/hbz/oerworldmap/issues/1720
Now descriptions with multiples languages look like this
This commit message is refered to react-tabs not react-select https://github.com/hbz/oerworldmap-ui/commit/aed7994a95f742748530ef98cb8e444b2ace8584
> Add react-tabs and logic for tabs

- src/common.js
Fixes: https://github.com/hbz/oerworldmap/issues/1774
The old addParamToURL function in common could not add parameters to relative URL's
> Refactor addParamToURL to accept relative URL

- src/router.js
Fixes: https://github.com/hbz/oerworldmap/issues/1764
Now profiles like https://oerworldmap.org/resource/urn:uuid:306f58c2-1107-45d2-87be-773fe2029736, with only a twitter picture will look like this
> Add twitter image to metadata

- src/components/Topline.js
- src/components/WebPageView.js
Fixes: https://github.com/hbz/oerworldmap/issues/1743
> Add encodeURIComponent to keywords links

- src/components/JSONPointerForm/MarkdownArea.js
Fixes: https://github.com/hbz/oerworldmap/issues/1744
> Set markdown-to-jsx as the only markdown render

- src/components/App.js
- src/styles/fonts.pcss
By importing only the fonts we use, the size of **dist** is reduced from `10,6 MB` to `7,5 MB`.
> Import only the fonts we use

- src/components/ResourceImage.js
Fixes: https://github.com/hbz/oerworldmap/issues/1880
With this branch we expect users to input images always under https,
> Remove http and https from user images

- src/styles/components/Columns.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1888
The content can be scrolled to continue the tour.
> Make the content scrollable for small screens

- src/styles/components/WebPageView.pcss
Fixes: https://github.com/hbz/oerworldmap/issues/1904
The padding was supposed to be 20 not -20
> Fix padding for Live Event

- src/components/TimelineBlock.js
Markdown parser in activty stream crashes if there is no comment field. As far as I can see, this happens when entry is deleted and there's a previous comment in the activity stream that is not there anymore.
This PR is just a simple check so we don't try to render invalid component.
Ref: https://github.com/hbz/oerworldmap/issues/1951
> Fixes crash in /activity if comment text is missing

- src/json/policyTypes.json
This PR updates "Call for tender" to be "Call for tender/proposal". It's rebased from https://github.com/hbz/oerworldmap-ui/pull/629 .
To deploy, from `oerworldmap-ui ` (please change `http://localhost:9000` to correct API location)
```
curl -H "Content-type: application/json" http://localhost:9000/import/ -d @src/json/policyTypes.json
```
Ref: https://github.com/hbz/oerworldmap/issues/1937
> Updates 'Call for tender' value

- src/components/WebPageView.js
This code adds a check if it's rendered for search engines/crawlers or if it's run in the browser. If it's run in the browser, then it displays e-mail section. It's not 100% optimal, but it's much more resource intensive on scrapers. At the end of the day, if we show this data to (non-logged in) visitor, then we can't hide it from a very resourcesful scraper. 
Ref: https://github.com/hbz/oerworldmap/issues/1936
> Don't render email address in server-side html to prevent scraping

- src/components/Export.js
- src/styles/components/Export.pcss
Defines all the existing export fields and adds exports for name and description for all languages and additional serviceUrl field.
Ref: https://github.com/hbz/oerworldmap/issues/1944
> Implements additional fields into CSV export
